import type { RtiDraft } from "../rti/rti";

const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const lines = (value: string) => value.split(/\r?\n/).map(escape).join("<br>");

export function renderRtiHtml(input: { referenceNumber: string; issuedAt: Date; content: RtiDraft }) {
  const { content } = input;
  if (content.status !== "READY" || !content.applicant || !content.publicAuthority || !content.subject || !content.informationRequests.length)
    throw new Error("INVALID_APPROVED_DOCUMENT");
  const date = new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "long", year: "numeric", timeZone: "Asia/Kolkata" }).format(input.issuedAt);
  const period = content.period && (content.period.from || content.period.to)
    ? `<p><strong>Period:</strong> ${escape(content.period.from || "Beginning of records")} to ${escape(content.period.to || "Present")}</p>` : "";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>${escape(input.referenceNumber)} RTI Application</title><style>
  @page{size:A4;margin:19mm 18mm 20mm}*{box-sizing:border-box}body{margin:0;color:#172420;font-family:Georgia,'Times New Roman',serif;font-size:11.5pt;line-height:1.62}header{border-bottom:2px solid #243a35;padding-bottom:12px;margin-bottom:22px;display:flex;justify-content:space-between;align-items:end}.brand{font-family:Arial,sans-serif;font-weight:800;letter-spacing:.13em;font-size:18pt;color:#243a35}.meta{text-align:right;font:9.5pt/1.45 Arial,sans-serif;color:#53635e}h1{text-align:center;font:700 15pt/1.3 Arial,sans-serif;letter-spacing:.08em;margin:24px 0}.date{text-align:right}.party{margin:14px 0}.label{display:block;font:700 8.5pt/1.4 Arial,sans-serif;letter-spacing:.1em;text-transform:uppercase;color:#62716c}.subject{margin:22px 0;padding:11px 13px;background:#f1f4f2;border-left:3px solid #315f55}ol{padding-left:24px}li{padding-left:8px;margin:0 0 12px;text-align:justify;break-inside:avoid}.applicant-contact{margin-top:18px;font-size:10.5pt}.signature{margin-top:42px}.signature-line{width:220px;border-top:1px solid #243a35;margin-top:48px;padding-top:7px}footer{margin-top:30px;border-top:1px solid #d8dfdc;padding-top:9px;font:8.5pt/1.4 Arial,sans-serif;color:#687772}
  </style></head><body><header><div class="brand">LAWMEDY</div><div class="meta">RTI application<br>${escape(input.referenceNumber)}</div></header><div class="date"><strong>Date:</strong> ${escape(date)}</div><div class="party"><span class="label">To</span><strong>The Public Information Officer</strong><br>${escape(content.publicAuthority.name)}<br>${escape(content.publicAuthority.department)}<br>${lines(content.publicAuthority.address)}</div><h1>APPLICATION FOR INFORMATION</h1><div class="subject"><strong>Subject:</strong> ${escape(content.subject)}</div>${period}<p>Sir/Madam,</p><p>I, <strong>${escape(content.applicant.name)}</strong>, a citizen of India, request the following information under Section 6(1) of the Right to Information Act, 2005:</p><ol>${content.informationRequests.map((request) => `<li>${escape(request.text)}</li>`).join("")}</ol><p>I request that the information be supplied within 30 days of receipt of this application as provided in Section 7(1) of the Act. I am enclosing the application fee as prescribed (payable by the mode accepted by the authority). If I am below the poverty line, a copy of my certificate is enclosed and no fee is payable. If the information concerns the life or liberty of a person, it should be supplied within 48 hours. If any part of the information is withheld, please state the provision relied on and the details of the appellate authority.</p><div class="applicant-contact"><strong>Applicant:</strong> ${escape(content.applicant.name)}${content.applicant.address ? `<br>${lines(content.applicant.address)}` : ""}${content.applicant.phone ? `<br>Phone: ${escape(content.applicant.phone)}` : ""}</div><div class="signature"><div class="signature-line"><strong>${escape(content.applicant.name)}</strong><br>Applicant</div></div><footer>This document was generated from the user-confirmed, versioned matter record.</footer></body></html>`;
}
